### ISSUE TITLE
About the Training Data GENERATION

### ISSUE THREAD

**Issue by yfaqh** [xuxy09/RawSR#4]
Hi, Xu, thank you for your team's great job! Actually, I have two questions about the training data and I beg for your soon reply.

Firstly, the format of the high-quality raw images(MIT-5k) is ".DNG", right? I think they should be bayer pattern images and every pixel there should be a detail intensity of R or G or B, but they just look like RGB images when I open them with PS. Or did I understand it wrong?

Secondly, could you please explain the details about the generation of desired images $X_lin$ which mentioned in your paper, the explanation in the paper is a little bit abstract.

Thanks a lot!

**Comment by xuxy09** [comment]
Hi, the raw data of MIT-5k is indeed a Bayer pattern image. I think PS must have used some ISP pipeline to convert the raw data into a normal RGB image for better visualization.

To get the original raw data and generate $X_lin$, as described in the paper, we use dcraw which has a good python API called rawpy which you can install via "pip install rawpy".
